// <auto-generated />
using System;
using Education.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Education.Persistence.Migrations
{
    [DbContext(typeof(EducationDbContext))]
    [Migration("20240320235618_EducationMigrationInitial")]
    partial class EducationMigrationInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Education.Domain.Curso", b =>
                {
                    b.Property<Guid>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = new Guid("f3b7268c-5bcb-4126-af5b-743d2272a945"),
                            Descripcion = "Curso de c# basico",
                            FechaCreacion = new DateTime(2024, 3, 20, 16, 56, 18, 417, DateTimeKind.Local).AddTicks(9708),
                            FechaPublicacion = new DateTime(2026, 3, 20, 16, 56, 18, 417, DateTimeKind.Local).AddTicks(9720),
                            Precio = 56m,
                            Titulo = "C# desde cero hasta avanzado"
                        },
                        new
                        {
                            CursoId = new Guid("8bb7afab-9933-41d3-862b-30c9d16cab74"),
                            Descripcion = "Curso de Java",
                            FechaCreacion = new DateTime(2024, 3, 20, 16, 56, 18, 417, DateTimeKind.Local).AddTicks(9766),
                            FechaPublicacion = new DateTime(2026, 3, 20, 16, 56, 18, 417, DateTimeKind.Local).AddTicks(9767),
                            Precio = 25m,
                            Titulo = "Master en Java Spring desde las raices"
                        },
                        new
                        {
                            CursoId = new Guid("37f02456-36b0-4079-b3fe-fd6165e2d4e3"),
                            Descripcion = "Curso de UnitTest para NET core",
                            FechaCreacion = new DateTime(2024, 3, 20, 16, 56, 18, 417, DateTimeKind.Local).AddTicks(9792),
                            FechaPublicacion = new DateTime(2026, 3, 20, 16, 56, 18, 417, DateTimeKind.Local).AddTicks(9792),
                            Precio = 1000m,
                            Titulo = "Master en UnitTest con CQRS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
